# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Smuek Constant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smuek Constant
  pod 'HGCircularSlider', '~> 2.2'

  target 'Smuek ConstantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Smuek ConstantUITests' do
    # Pods for testing
  end

end
